### ISSUE TITLE
How to handle onConnectionInterrupted callback due to connection close in 24 hours

### ISSUE THREAD

**Issue by cyber274** [aws/aws-iot-device-sdk-cpp-v2#771]
### Describe the bug

We are creating MQTT connection(software.amazon.awssdk.crt.mqtt.MqttClientConnection) over WebSocket using IAM Role credentials. The connection gets successfully created and we are able to listen to incoming events. 

However, we noticed that MQTT connection gets closed unexpectedly in 24 hours due to IOT Core [limitation](https://docs.aws.amazon.com/general/latest/gr/iot-core.html#limits_iot). And the connection does not resume automatically. 

This is the code.
 {
final EventLoopGroup eventLoopGroup = new EventLoopGroup(1);
            final ClientBootstrap clientBootstrap = new ClientBootstrap(eventLoopGroup,
                    new HostResolver(eventLoopGroup));

            final SocketOptions socketOptions = new SocketOptions();
            socketOptions.keepAliveTimeoutSecs = 30;
            socketOptions.keepAliveIntervalSecs = 5;
            socketOptions.keepAlive = true;

            return AwsIotMqttConnectionBuilder.newDefaultBuilder()
                    .withBootstrap(clientBootstrap)
                    .withClientId(iotConnectClientId)
                    .withEndpoint(iotCoreEndpoint)
                    .withWebsockets(true)
                    .withReconnectTimeoutSecs(1, 60)
                    .withWebsocketSigningRegion(region)
                    .withProtocolOperationTimeoutMs(30 * 1000)
                    .withPingTimeoutMs(15 * 1000)
                    .withWebsocketCredentialsProvider(credentialsProvider)
                    .withKeepAliveSecs(60)
                    .withSocketOptions(socketOptions)
                    .withTimeoutMs(30 * 1000)
                    .withCleanSession(false)
                    .withConnectionEventCallbacks(getMqttClientConnectionEvents(siteId, eventLoopGroup))
                    .build();

        } catch (final Exception e) {
            log.error("Exception while creating AwsIotMqtt Connection", e);
            throw e;
        }
}

We receive error code: 5134 and error message "string: The connection was closed unexpectedly. for MQTT topic: <MQTT topic>". in onConnectionInterrupted() callback method. 

We tried to call mqttSecondaryConnection.connect().get(10, TimeUnit.SECONDS); as reconnect() in onConnectionInterrupted() callback method but we received: 

java.util.concurrent.ExecutionException: software.amazon.awssdk.crt.CrtRuntimeException: MqttClientConnection.mqtt_connect: aws_mqtt_client_connection_connect failed (aws_last_error: AWS_ERROR_MQTT_ALREADY_CONNECTED(5132), The requested operation is invalid as the connection is already open.) AWS_ERROR_MQTT_ALREADY_CONNECTED(5132) at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?] at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096) ~[?:?] at ...

Can anybody help, how to reconnect in this case ?

### Expected Behavior

The connection should resume automatically.

### Current Behavior

The connection does not resume in this case.

### Reproduction Steps

Create the fresh connection after 24 hours to see the connection closure after 24 hours.

### SDK version used

JDK17

### Environment details (OS name and version, etc.)

IOT Core

**Comment by bretambrose** [comment]
The client will always reconnect in the scenario you have described.  If you have CRT logs showing otherwise, please attach them.

**Comment by cyber274** [comment]
Created new issue in v2 Java SDK repository with the error log. https://github.com/aws/aws-iot-device-sdk-java-v2/issues/607
Can you please have a look.

**Comment by cyber274** [comment]
> The client will always reconnect in the scenario you have described.

Also, Can you explain this line "The client will always reconnect in the scenario you have described." Did you mean, the client reconnects automatically or the client needs to fire some code to reconnect ?

**Comment by bretambrose** [comment]
"the client reconnects automatically"

**Comment by jmklix** [comment]
Closing this in favor of the other issue that you [opened](https://github.com/aws/aws-iot-device-sdk-java-v2/issues/607)
